#!/usr/bin/env bash
# Post the rendered "🔔 Waiting on you" digest as a comment on the single standing
# issue, creating that issue the first time if it doesn't exist. Reuses one rolling
# issue (like the housekeeping/epic digests) so there's no notification spam.
# Auth via gh + GH_TOKEN. Report-only — this touches nothing but its own standing issue.
#
#   GH_TOKEN=... DIGEST_BODY_FILE=waiting-on-you.md bash post-comment.sh
set -euo pipefail

REPO="${DIGEST_REPO:-FriendlyInternet/nuxt-crouton}"
TITLE="${WAITING_ON_YOU_ISSUE_TITLE:-🔔 Waiting on you}"
BODY_FILE="${DIGEST_BODY_FILE:-waiting-on-you.md}"

# Find the standing issue via the REST list API (immediately consistent) — NOT
# `gh issue list --search`, whose index lags right after the issue is created.
find_issue() {
  gh issue list --repo "$REPO" --state open --label meta:agents --limit 500 \
    --json number,title --jq ".[] | select(.title==\"$TITLE\") | .number" | head -n1
}

num="$(find_issue || true)"

if [ -z "${num:-}" ]; then
  echo "No standing issue found — creating it."
  created="$(gh issue create --repo "$REPO" --title "$TITLE" --label meta:agents,workflow --body \
"Standing home for the **\"waiting on you\" digest**. On its schedule, the \`waiting-on-you\` workflow posts a fresh comment here — a single list of every open issue/PR currently holding on an owner gesture (a question to answer, an action only you can take, or a diff/preview to approve).

It is **report-only**: nothing in here is auto-changed. Generated by \`.github/workflows/waiting-on-you.yml\` (deterministic, no LLM). Don't close this issue.")"
  num="$(printf '%s' "$created" | grep -oE '[0-9]+$' | tail -n1)"
fi

if [ -z "${num:-}" ]; then
  echo "Could not find or create the standing issue." >&2
  exit 1
fi

echo "Posting waiting-on-you digest comment to #$num"
gh issue comment "$num" --repo "$REPO" --body-file "$BODY_FILE"
