#!/usr/bin/env node
/**
 * Render the "🔔 Waiting on you" digest data (from gather.mjs) into Markdown.
 *
 *   node render.mjs waiting-on-you.data.json [--out-dir .]
 *
 * Render-only: JSON → text → file. Never calls GitHub. Grouped by the kind of owner
 * action needed (answer / action / approval, the #2067 vocabulary) so the owner can
 * triage top-to-bottom. Mirrors the shape of .claude/skills/housekeeping/render.mjs.
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { BRAND_NAME, BRAND_URL } from '../../../packages/crouton-email/brand/email-brand.mjs'

const args = process.argv.slice(2)
const dataPath = args.find((a) => !a.startsWith('--'))
if (!dataPath) {
  console.error('render.mjs: pass the path to waiting-on-you.data.json')
  process.exit(1)
}
const outDir = (() => {
  const i = args.indexOf('--out-dir')
  return i >= 0 ? args[i + 1] : '.'
})()

const data = JSON.parse(readFileSync(dataPath, 'utf8'))
const link = (n, t, url) => `[#${n}](${url}) — ${t}`
const entryLine = (e) => `- ${link(e.number, e.title, e.url)}${e.draft ? ' _(draft)_' : ''} — idle ${e.ageDays}d`

const GROUPS = [
  ['answer', '🔀 Needs an answer', 'A question is waiting for you to pick between options:'],
  ['action', '🛠 Needs an action', 'The agent can\'t do this itself — it needs you to do something (often applying a workflow patch):'],
  ['approval', '👀 Needs approval', 'A diff or preview is ready for your review:']
]

const sections = []
for (const [key, title, lead] of GROUPS) {
  const entries = data[key] || []
  if (!entries.length) continue
  sections.push([title, [lead, ...entries.map(entryLine)]])
}

const when = new Date(data.generatedAt).toISOString().slice(0, 10)
const total = GROUPS.reduce((sum, [key]) => sum + (data[key]?.length || 0), 0)
const head = [`## 🔔 Waiting on you — ${when}`, '']
const body = sections.length
  ? sections.flatMap(([h, lines]) => [`### ${h}`, ...lines, ''])
  : ["✨ Nothing is waiting on you right now.", '']
const foot = [
  '---',
  `_[${BRAND_NAME}](${BRAND_URL}) · Render-only digest · ${total} item(s) · nothing here was modified. Generated by \`.github/workflows/waiting-on-you.yml\`._`
]
const md = [...head, ...body, ...foot].join('\n') + '\n'

const outFile = join(outDir, `waiting-on-you-${when}.md`)
writeFileSync(outFile, md)
process.stdout.write(`Wrote ${outFile}\n`)
