// Generator for _Form.vue component
import { toCase } from '../utils/helpers.ts'

/**
 * Generate AI context header for _Form.vue components
 */
function generateAIHeader(data: Record<string, any>, apiPath: string): string {
  const { plural, layer, layerPascalCase, pascalCasePlural, fields } = data
  const fieldNames = fields.filter(f => f.name !== 'id').map(f => f.name).join(', ')

  return `<!--
  @crouton-generated
  @collection ${plural}
  @layer ${layer}
  @generated ${new Date().toISOString().split('T')[0]}

  ## AI Context
  - Form component for ${plural} collection
  - Handles: create, update, delete actions
  - API endpoint: /api/teams/[id]/${apiPath}
  - Zod schema: use${layerPascalCase}${pascalCasePlural}() composable
  - Fields: ${fieldNames}

  ## Common Modifications
  - Add field: Add UFormField in template, update schema in composable
  - Custom validation: Modify schema in composable
  - Custom field component: Use meta.component in schema JSON
  - Change layout: Modify CroutonFormLayout template slots

  Generated by @fyit/crouton-cli
  Safe to modify - regeneration requires --force flag
-->

`
}

// Helper: Group fields by their group meta value
function groupFieldsByGroup(fields: Record<string, any>[]): Map<string | null, Record<string, any>[]> {
  const grouped = new Map()
  fields.forEach((field) => {
    const group = field.meta?.group || null
    if (!grouped.has(group)) {
      grouped.set(group, [])
    }
    grouped.get(group).push(field)
  })
  return grouped
}

// Helper: Convert 'seoSettings' to 'SEO Settings'
function humanizeGroupName(groupName: string | null): string {
  if (!groupName) return 'General'
  return groupName
    .replace(/([A-Z])/g, ' $1')
    .replace(/^./, str => str.toUpperCase())
    .trim()
}

// Helper: Convert a camelCase field name to a human-readable fallback label
// e.g., 'eventOrderNumber' → 'Event Order Number'
function humanizeFieldName(fieldName: string): string {
  return fieldName
    .replace(/([A-Z])/g, ' $1')
    .replace(/^./, str => str.toUpperCase())
    .trim()
}

// Helper: Escape single quotes/backslashes for embedding a string in a single-quoted JS literal
function escapeLabel(value: unknown): string {
  return String(value).replace(/\\/g, '\\\\').replace(/'/g, "\\'")
}

// Helper: Convert snake_case or kebab-case to human-readable label
// e.g., 'booking_created' → 'Booking Created'
function formatOptionLabel(value: unknown): string {
  if (typeof value !== 'string') return String(value)
  return value
    .replace(/[-_]/g, ' ')
    .replace(/\b\w/g, char => char.toUpperCase())
}

// Helper to resolve component names (handles component aliasing)
function resolveComponentName(componentName: string): string {
  // Transform EditorSimple to CroutonEditorSimple to match actual registration
  if (componentName === 'EditorSimple') {
    return 'CroutonEditorSimple'
  }
  // Transform ColorPicker to CroutonFormColorPicker (popover-based picker with presets)
  if (componentName === 'ColorPicker') {
    return 'CroutonFormColorPicker'
  }
  return componentName
}

// ── i18n field labels ──────────────────────────────────────────────────────
// Field labels resolve through useT() so they can be translated/overridden per
// team, with a humanized fallback so untranslated keys still render readable text.
// Key convention: `{layer}.{plural}.fields.{fieldName}` (seed these in your locales).
function createLabelAttr(fieldsI18nPrefix: string) {
  return (field: Record<string, any>, fallbackOverride?: string): string => {
    const fallback = fallbackOverride ?? field.meta?.label ?? humanizeFieldName(field.name)
    return `:label="t('${fieldsI18nPrefix}.${field.name}', '${escapeLabel(fallback)}')"`
  }
}

// ── Field markup rendering ─────────────────────────────────────────────────
// Per-collection values the module-scope field/group renderers need (so they
// don't close over generateFormComponent locals).
interface FieldMarkupContext {
  layerCamelCase: string
  layerPascalCase: string
  pascalCasePlural: string
  formEnhancements: Record<string, any>
  labelAttr: (field: Record<string, any>, fallbackOverride?: string) => string
}

// Field with a custom component specified in meta (e.g. EditorSimple)
function renderCustomComponentField(field: Record<string, any>, ctx: FieldMarkupContext): string {
  const componentName = resolveComponentName(field.meta.component)
  return `        <UFormField ${ctx.labelAttr(field)} name="${field.name}" class="not-last:pb-4">
          <${componentName} v-model="state.${field.name}" />
        </UFormField>`
}

// Dependent field (slotButtonGroup): options load from another field's selected value
function renderDependentField(field: Record<string, any>, ctx: FieldMarkupContext): string {
  const dependsOn = field.meta.dependsOn
  const dependsOnField = field.meta.dependsOnField
  const dependsOnCollection = field.meta.dependsOnCollection

  // Resolve the collection name with layer prefix
  const refCases = toCase(dependsOnCollection)
  const resolvedCollection = `${ctx.layerCamelCase}${refCases.pascalCasePlural}`

  // Determine dependent label (capitalize first letter)
  const dependentLabel = dependsOn.charAt(0).toUpperCase() + dependsOn.slice(1)

  return `        <UFormField ${ctx.labelAttr(field)} name="${field.name}" class="not-last:pb-4">
          <CroutonFormDependentFieldLoader
            v-model="state.${field.name}"
            :dependent-value="state.${dependsOn}"
            dependent-collection="${resolvedCollection}"
            dependent-field="${dependsOnField}"
            dependent-label="${dependentLabel}"
          />
        </UFormField>`
}

// Static options select field (inline meta.options array → `${name}Options` const in the script)
function renderInlineOptionsField(field: Record<string, any>, ctx: FieldMarkupContext): string {
  return `        <UFormField ${ctx.labelAttr(field)} name="${field.name}" class="not-last:pb-4">
          <USelect
            v-model="state.${field.name}"
            :items="${field.name}Options"
            class="w-full"
            size="xl"
          />
        </UFormField>`
}

// Options select field backed by an options collection (admin-configurable dropdown)
function renderOptionsCollectionField(field: Record<string, any>, ctx: FieldMarkupContext): string {
  const optionsCollection = field.meta.optionsCollection
  const optionsField = field.meta.optionsField
  const creatable = field.meta.creatable !== false // Default to true

  // Resolve the collection name with layer prefix
  // If optionsCollection already starts with layer prefix, use as-is
  // Otherwise add the layer prefix (for backwards compatibility with short names like "settings")
  let resolvedOptionsCollection
  if (optionsCollection.startsWith(ctx.layerCamelCase)) {
    // Already has prefix (e.g., "bookingsSettings")
    resolvedOptionsCollection = optionsCollection
  } else {
    // Add prefix (e.g., "settings" -> "bookingsSettings")
    const refCases = toCase(optionsCollection)
    resolvedOptionsCollection = `${ctx.layerCamelCase}${refCases.pascalCasePlural}`
  }

  return `        <UFormField ${ctx.labelAttr(field)} name="${field.name}" class="not-last:pb-4">
          <CroutonFormOptionsSelect
            v-model="state.${field.name}"
            options-collection="${resolvedOptionsCollection}"
            options-field="${optionsField}"
            ${ctx.labelAttr(field)}${!creatable
              ? `
            :creatable="false"`
              : ''}
          />
        </UFormField>`
}

// Reference field (has refTarget): read-only card, multi-select or single reference select
function renderReferenceField(field: Record<string, any>, ctx: FieldMarkupContext): string {
  let resolvedCollection

  // Check refScope to determine how to resolve the reference
  if (field.refScope === 'adapter') {
    // Adapter-scoped reference: use target as-is (no layer prefix)
    // These are managed by connector packages (e.g., @fyit/crouton-supersaas)
    resolvedCollection = field.refTarget
  } else {
    // Local layer reference: add layer prefix
    const refCases = toCase(field.refTarget)
    resolvedCollection = `${ctx.layerCamelCase}${refCases.pascalCasePlural}`
  }

  // Check if this is a read-only reference field
  if (field.meta?.readOnly) {
    return `        <UFormField ${ctx.labelAttr(field)} name="${field.name}" class="not-last:pb-4">
          <CroutonItemCardMini
            v-if="state.${field.name}"
            :id="state.${field.name}"
            collection="${resolvedCollection}"
          />
          <span v-else class="text-gray-400 text-sm">Not set</span>
        </UFormField>`
  }

  // Build optional label-key and filter-fields props when labelField is specified
  const labelField = field.meta?.labelField
  const labelKeyAttr = labelField && labelField !== 'title'
    ? `\n            label-key="${labelField}"\n            :filter-fields="['${labelField}']"`
    : ''

  // Check if this is an array type (multi-select reference)
  if (field.type === 'array') {
    return `        <UFormField ${ctx.labelAttr(field)} name="${field.name}" class="not-last:pb-4">
          <CroutonFormReferenceSelect
            v-model="state.${field.name}"
            collection="${resolvedCollection}"
            ${ctx.labelAttr(field)}${labelKeyAttr}
            multiple
          />
        </UFormField>`
  }

  return `        <UFormField ${ctx.labelAttr(field)} name="${field.name}" class="not-last:pb-4">
          <CroutonFormReferenceSelect
            v-model="state.${field.name}"
            collection="${resolvedCollection}"
            ${ctx.labelAttr(field)}${labelKeyAttr}
          />
        </UFormField>`
}

// Fallback rendering keyed on the field's (canonical) type
function renderDefaultTypeField(field: Record<string, any>, ctx: FieldMarkupContext): string {
  const { labelAttr } = ctx

  // Image field type — base fallback uses CroutonImageUpload (crouton-assets contribution overrides with CroutonAssetsPicker)
  if (field.type === 'image') {
    return `        <UFormField ${labelAttr(field)} name="${field.name}" class="not-last:pb-4">
          <CroutonImageUpload
            v-model="state.${field.name}"
            :crop="true"
          />
        </UFormField>`
  }

  // File field type — base fallback uses CroutonImageUpload
  if (field.type === 'file') {
    return `        <UFormField ${labelAttr(field)} name="${field.name}" class="not-last:pb-4">
          <CroutonImageUpload
            v-model="state.${field.name}"
          />
        </UFormField>`
  }

  // Default component selection based on field type
  if (field.type === 'text') {
    return `        <UFormField ${labelAttr(field)} name="${field.name}" class="not-last:pb-4">
          <UTextarea v-model="state.${field.name}" class="w-full" size="xl" />
        </UFormField>`
  } else if (field.type === 'boolean') {
    return `        <UFormField ${labelAttr(field)} name="${field.name}" class="not-last:pb-4">
          <UCheckbox v-model="state.${field.name}" />
        </UFormField>`
  } else if (field.type === 'number' || field.type === 'decimal') {
    return `        <UFormField ${labelAttr(field)} name="${field.name}" class="not-last:pb-4">
          <UInputNumber v-model="state.${field.name}" class="w-full" />
        </UFormField>`
  } else if (field.type === 'date') {
    const pickerProp = field.meta?.picker ? ' picker' : ''
    return `        <UFormField ${labelAttr(field)} name="${field.name}" class="not-last:pb-4">
          <CroutonCalendar v-model:date="state.${field.name}"${pickerProp} />
        </UFormField>`
  } else if (field.type === 'repeater') {
    // Use the field's Input component from the field components folder
    const fieldCases = toCase(field.name)
    const componentName = `${ctx.layerPascalCase}${ctx.pascalCasePlural}${fieldCases.pascalCase}Input`
    const addLabel = field.meta?.addLabel || 'Add Item'
    const sortable = field.meta?.sortable !== false // Default to true

    return `        <UFormField ${labelAttr(field)} name="${field.name}" class="not-last:pb-4">
          <CroutonFormRepeater
            v-model="state.${field.name}"
            component-name="${componentName}"
            add-label="${addLabel}"
            ${sortable ? ':sortable="true"' : ':sortable="false"'}
          />
        </UFormField>`
  } else if (field.type === 'json') {
    // JSON field - use textarea with JSON serialization
    return `        <UFormField ${labelAttr(field)} name="${field.name}" class="not-last:pb-4">
          <UTextarea
            :model-value="typeof state.${field.name} === 'string' ? state.${field.name} : JSON.stringify(state.${field.name}, null, 2)"
            @update:model-value="(val) => { try { state.${field.name} = val ? JSON.parse(val) : {} } catch (e) { console.error('Invalid JSON:', e) } }"
            class="w-full font-mono text-sm"
            :rows="8"
            placeholder="Enter JSON object"
          />
        </UFormField>`
  } else if (field.type === 'array' && !field.refTarget) {
    // Array field without refTarget - use textarea with array handling
    return `        <UFormField ${labelAttr(field)} name="${field.name}" class="not-last:pb-4">
          <UTextarea
            :model-value="Array.isArray(state.${field.name}) ? state.${field.name}.join('\\n') : ''"
            @update:model-value="(val) => state.${field.name} = val ? val.split('\\n').filter(Boolean) : []"
            class="w-full"
            :rows="6"
            placeholder="Enter one value per line"
          />
          <p class="text-sm text-gray-500 mt-1">Enter one value per line</p>
        </UFormField>`
  } else {
    return `        <UFormField ${labelAttr(field)} name="${field.name}" class="not-last:pb-4">
          <UInput v-model="state.${field.name}" class="w-full" size="xl" />
        </UFormField>`
  }
}

// Render the form markup for one field, dispatching to the renderer matching its
// meta/type shape. Order matters: contribution overrides win, then explicit
// component/display hints, then references, then type-based defaults.
function generateFieldMarkup(field: Record<string, any>, ctx: FieldMarkupContext): string {
  // ── Contribution override takes priority ─────────────────────────────
  const override = ctx.formEnhancements.fieldOverrides?.[field.name]
  if (override !== undefined) {
    // Empty string means hide the field; otherwise use the override template
    return override
  }

  // Check if a custom component is specified in meta
  if (field.meta?.component) {
    return renderCustomComponentField(field, ctx)
  }

  // Check if this is a dependent field
  if (field.meta?.displayAs === 'slotButtonGroup' && field.meta?.dependsOn && field.meta?.dependsOnField && field.meta?.dependsOnCollection) {
    return renderDependentField(field, ctx)
  }

  // Check if this is a static options select field (inline meta.options array)
  if (field.meta?.displayAs === 'optionsSelect' && Array.isArray(field.meta?.options) && !field.meta?.optionsCollection) {
    return renderInlineOptionsField(field, ctx)
  }

  // Check if this is an options select field (admin-configurable dropdown)
  if (field.meta?.displayAs === 'optionsSelect' && field.meta?.optionsCollection && field.meta?.optionsField) {
    return renderOptionsCollectionField(field, ctx)
  }

  // Check if this is a reference field (has refTarget)
  if (field.refTarget) {
    return renderReferenceField(field, ctx)
  }

  return renderDefaultTypeField(field, ctx)
}

// ── Field analysis ─────────────────────────────────────────────────────────
// Derive the field partitions and feature flags the generator branches on:
// hierarchy handling, translatable vs regular fields, contribution exclusions,
// and the display / inline-options lists.
function analyzeFields(data: Record<string, any>, config: Record<string, any>) {
  const { fields, plural, hierarchy } = data

  // Check for hierarchy support
  const hasHierarchy = hierarchy?.enabled === true
  const parentField = hierarchy?.parentField || 'parentId'

  // Check for translations
  const translatableFieldNames = config?.translations?.collections?.[plural] || []
  const hasTranslations = translatableFieldNames.length > 0

  // Define hierarchy fields to exclude from regular field processing
  // These are auto-generated by the database schema generator and have special handling
  const hierarchyFields = hasHierarchy
    ? [
        parentField,
        hierarchy.pathField || 'path',
        hierarchy.depthField || 'depth',
        hierarchy.orderField || 'order'
      ]
    : []

  // Separate fields
  const translatableFields = fields.filter(f => translatableFieldNames.includes(f.name))
  const regularFields = fields.filter(f =>
    f.name !== 'id'
    && !translatableFieldNames.includes(f.name)
    && !hierarchyFields.includes(f.name)
  )

  // Check if we have any date fields
  const hasDateFields = regularFields.some(field => field.type === 'date')

  // ── Contribution-driven enhancements ─────────────────────────────────────
  // formEnhancements is populated by runFormContributions() in generate-collection.ts
  const formEnhancements = data.formEnhancements || {
    excludeFieldNames: [],
    groupInjections: {},
    fieldOverrides: {},
    scriptAdditions: [],
  }

  // Fields excluded from normal rendering (e.g. coordinate field hidden by map contribution)
  const excludedFieldNames = new Set<string>(formEnhancements.excludeFieldNames || [])

  // ── Field display list ────────────────────────────────────────────────────
  // Filter out fields excluded by contributions (e.g. coordinate field when map is shown)
  const fieldsToDisplay = regularFields.filter(field => !excludedFieldNames.has(field.name))

  // Track fields with inline options for script generation (static USelect options)
  const fieldsWithInlineOptions = fieldsToDisplay.filter(
    f => f.meta?.displayAs === 'optionsSelect'
      && Array.isArray(f.meta?.options)
      && !f.meta?.optionsCollection
  )

  return {
    hasHierarchy,
    parentField,
    translatableFieldNames,
    hasTranslations,
    translatableFields,
    regularFields,
    hasDateFields,
    formEnhancements,
    excludedFieldNames,
    fieldsToDisplay,
    fieldsWithInlineOptions
  }
}

// ── Group assembly ─────────────────────────────────────────────────────────
// Group the displayable fields by area (main/sidebar) and then by group,
// ensuring groups that have contribution injections exist in the maps
// (e.g. the coordinate field's group may be filtered out but we still need to inject the map)
function buildFieldGroups(
  fieldsToDisplay: Record<string, any>[],
  fields: Record<string, any>[],
  excludedFieldNames: Set<string>,
  formEnhancements: Record<string, any>
) {
  // Group fields by area and then by group
  const mainFields = fieldsToDisplay.filter(f => !f.meta?.area || f.meta.area === 'main')
  const sidebarFields = fieldsToDisplay.filter(f => f.meta?.area === 'sidebar')

  const mainGroups = groupFieldsByGroup(mainFields)
  const sidebarGroups = groupFieldsByGroup(sidebarFields)

  for (const groupName of Object.keys(formEnhancements.groupInjections || {})) {
    if (!mainGroups.has(groupName === '' ? null : groupName) && !sidebarGroups.has(groupName === '' ? null : groupName)) {
      // Check if the excluded field that belonged to this group was main or sidebar
      const excludedField = fields.find(f =>
        excludedFieldNames.has(f.name) && (f.meta?.group || null) === (groupName || null)
      )
      const targetGroups = excludedField?.meta?.area === 'sidebar' ? sidebarGroups : mainGroups
      if (!targetGroups.has(groupName || null)) {
        targetGroups.set(groupName || null, [])
      }
    }
  }

  return { mainGroups, sidebarGroups }
}

// Helper to generate a group section with flex layout
function buildGroupSection(groupName: string | null, groupFields: Record<string, any>[], showConditionally: boolean, ctx: FieldMarkupContext): string {
  const groupValue = groupName || 'general'
  const fieldsMarkup = groupFields.map(field => generateFieldMarkup(field, ctx)).join('\n')

  // Inject contribution-provided content after this group
  const groupKey = groupName || ''
  const groupInjection = ctx.formEnhancements.groupInjections?.[groupKey] || ''

  const conditionalWrapper = showConditionally
    ? `      <div v-show="!tabs || activeSection === '${groupValue}'" class="flex flex-col gap-4 p-1">\n`
    : `      <div class="flex flex-col gap-4 p-1">\n`

  return `${conditionalWrapper}${fieldsMarkup}${groupInjection}
      </div>`
}

// ── Template section builders ──────────────────────────────────────────────

// Generate parent picker section for hierarchy-enabled collections
// This uses CroutonFormParentSelect which excludes self and descendants
function buildParentPickerSection(hasHierarchy: boolean, parentField: string, layerCamelCase: string, pascalCasePlural: string): string {
  return hasHierarchy
    ? `
        <UFormField :label="t('crouton.form.parent', 'Parent')" name="${parentField}" class="not-last:pb-4">
          <CroutonFormParentSelect
            v-model="state.${parentField}"
            collection="${layerCamelCase}${pascalCasePlural}"
            :current-id="state.id"
            :label="t('crouton.form.parent', 'Parent')"
          />
        </UFormField>`
    : ''
}

// Add CroutonI18nInput if there are translatable fields
// Use fallback to empty string to ensure string type compatibility
function buildTranslationField(hasTranslations: boolean, translatableFieldNames: string[], translatableFields: Record<string, any>[], plural: string): string {
  // Build fieldComponents map for translatable fields with custom components
  const fieldComponentsMap: Record<string, string> = {}
  translatableFields.forEach((field) => {
    if (field.meta?.component) {
      fieldComponentsMap[field.name] = resolveComponentName(field.meta.component)
    }
  })
  const hasFieldComponents = Object.keys(fieldComponentsMap).length > 0

  return hasTranslations
    ? `

      <CroutonI18nInput
        v-model="state.translations"
        :fields="[${translatableFieldNames.map(f => `'${f}'`).join(', ')}]"
        :default-values="{
          ${translatableFields.map(f => `${f.name}: state.${f.name} || ''`).join(',\n          ')}
        }"${hasFieldComponents
          ? `
        :field-components="{
          ${Object.entries(fieldComponentsMap).map(([field, component]) => `${field}: '${component}'`).join(',\n          ')}
        }"`
          : ''}
        show-ai-translate
        field-type="${plural}"
        :label="t('crouton.form.translations', 'Translations')"
      />`
    : ''
}

// ── Script section builders ────────────────────────────────────────────────

// Generate navigation items array for the template (tabbed forms)
function buildNavigationItemsCode(useTabs: boolean, navigationItems: Array<{ label: string, value: string }>): string {
  return useTabs
    ? `const navigationItems = [
  ${navigationItems.map(item => `{ label: '${item.label}', value: '${item.value}' }`).join(',\n  ')}
]

const tabs = ref(true)
const activeSection = ref('${navigationItems[0]?.value || 'general'}')`
    : 'const tabs = ref(false)'
}

// Generate inline options arrays for static USelect fields
function buildInlineOptionsCode(fieldsWithInlineOptions: Record<string, any>[]): string {
  return fieldsWithInlineOptions.length > 0
    ? fieldsWithInlineOptions.map((field) => {
        const options = field.meta.options
        const optionsArray = options.map((opt) => {
          // Support both string values and {label, value} objects
          if (typeof opt === 'object' && opt !== null && opt.label && opt.value !== undefined) {
            return `  { label: '${opt.label}', value: '${opt.value}' }`
          }
          return `  { label: '${formatOptionLabel(opt)}', value: '${opt}' }`
        }).join(',\n')
        return `const ${field.name}Options = [\n${optionsArray}\n]`
      }).join('\n\n')
    : ''
}

// Generate field-to-group mapping for error tracking
function buildFieldToGroupCode(useTabs: boolean, mainGroups: Map<string | null, Record<string, any>[]>): string {
  const fieldGroupMapping = useTabs ? mainGroups : new Map()
  return useTabs
    ? `
// Map field names to their tab groups for error tracking
const fieldToGroup: Record<string, string> = {
${Array.from(fieldGroupMapping.entries())
  .flatMap(([groupName, fields]) =>
    fields.map(field => `  '${field.name}': '${groupName || 'general'}'`)
  )
  .join(',\n')}
}`
    : ''
}

// Error tracking code (only emitted if tabs are used)
const ERROR_TRACKING_CODE = `
// Track validation errors for tab indicators
const validationErrors = ref<Array<{ name: string; message: string }>>([])

// Handle form validation errors
const handleValidationError = (event: any) => {
  if (event?.errors) {
    validationErrors.value = event.errors
  }
}

// Compute errors per tab
const tabErrorCounts = computed(() => {
  const counts: Record<string, number> = {}

  validationErrors.value.forEach(error => {
    const tabName = fieldToGroup[error.name] || 'general'
    counts[tabName] = (counts[tabName] || 0) + 1
  })

  return counts
})

// Switch to a specific tab (for clicking error links)
const switchToTab = (tabValue: string) => {
  activeSection.value = tabValue
}`

// Hierarchy defaults snippet: new items get parentId/path/depth/order seeded
function buildHierarchyDefaultsCode(hasHierarchy: boolean, hierarchy: Record<string, any>, parentField: string): string {
  return hasHierarchy
    ? `
// Hierarchy defaults for new items (parentId, path, depth, order)
const hierarchyDefaults = {
  ${parentField}: null,
  ${hierarchy.pathField || 'path'}: '/',
  ${hierarchy.depthField || 'depth'}: 0,
  ${hierarchy.orderField || 'order'}: 0
}`
    : ''
}

// Date-hydration snippet: convert stored ISO strings to Date objects when editing
function buildDateInitCode(hasDateFields: boolean, regularFields: Record<string, any>[]): string {
  return hasDateFields
    ? `

// Convert date strings to Date objects for date fields during editing
if (props.action === 'update' && props.activeItem?.id) {${regularFields
  .filter(f => f.type === 'date')
  .map(field => `
  if (initialValues.${field.name}) {
    initialValues.${field.name} = new Date(initialValues.${field.name})
  }`).join('')}
}`
    : ''
}

// The generated handleSubmit body (create/update/delete + optional date serialization)
function buildHandleSubmitCode(hasDateFields: boolean, regularFields: Record<string, any>[], useTabs: boolean): string {
  return `const handleSubmit = async () => {
  try {${hasDateFields
    ? `
    // Serialize Date objects to ISO strings for API submission
    const serializedData: Record<string, any> = { ...state.value }${regularFields
      .filter(f => f.type === 'date')
      .map(field => `
    if (serializedData.${field.name} instanceof Date) {
      serializedData.${field.name} = serializedData.${field.name}.toISOString()
    }`).join('')}
`
    : ''}
    if (props.action === 'create') {
      await create(${hasDateFields ? 'serializedData' : 'state.value'})
    } else if (props.action === 'update' && state.value.id) {
      await update(state.value.id, ${hasDateFields ? 'serializedData' : 'state.value'})
    } else if (props.action === 'delete') {
      await deleteItems(props.items)
    }
${useTabs
  ? `
    // Clear validation errors on successful submission
    validationErrors.value = []
`
  : ''}
    close()

  } catch (error) {
    console.error('Form submission failed:', error)
    // You can add toast notification here if available
    // toast.add({ title: 'Error', description: 'Failed to submit form', color: 'red' })
  }
}`
}

// ── SFC assembly ───────────────────────────────────────────────────────────

// Assemble the <template> half of the generated SFC
function renderTemplateSection(opts: {
  useTabs: boolean
  mainAreaMarkup: string
  translationField: string
  hasSidebar: boolean
  hasHierarchy: boolean
  parentPickerSection: string
  sidebarAreaMarkup: string
}): string {
  const { useTabs, mainAreaMarkup, translationField, hasSidebar, hasHierarchy, parentPickerSection, sidebarAreaMarkup } = opts

  return `<template>
  <CroutonFormActionButton
    v-if="action === 'delete'"
    :action="action"
    :collection="collection"
    :items="items"
    :loading="loading"
    @click="handleSubmit"
  />

  <UForm
    v-else
    :schema="schema"
    :state="state"
    @submit="handleSubmit"${useTabs
      ? `
    @error="handleValidationError"`
      : ''}
  >
    <CroutonFormLayout${useTabs ? ' :tabs="tabs" :navigation-items="navigationItems" :tab-errors="tabErrorCounts" v-model="activeSection"' : ''}>
      <template #main${useTabs ? '="{ activeSection }"' : ''}>
${mainAreaMarkup}${translationField ? `\n\n      <div>\n${translationField}\n      </div>` : ''}
      </template>
${hasSidebar
  ? `
      <template #sidebar>
      <div class="flex flex-col gap-4 p-1">${hasHierarchy
        ? `
${parentPickerSection}`
        : ''}
      </div>
${sidebarAreaMarkup}
      </template>
`
  : ''}
      <template #footer>${useTabs
        ? `
        <CroutonValidationErrorSummary
          v-if="validationErrors.length > 0"
          :tab-errors="tabErrorCounts"
          :navigation-items="navigationItems"
          @switch-tab="switchToTab"
        />
`
        : ''}
        <CroutonFormActionButton
          :action="action"
          :collection="collection"
          :items="items"
          :loading="loading"${useTabs
            ? `
          :has-validation-errors="validationErrors.length > 0"`
            : ''}
        />
      </template>
    </CroutonFormLayout>
  </UForm>
</template>`
}

// Assemble the <script setup> half of the generated SFC
function renderScriptSection(opts: {
  prefixedPascalCase: string
  prefixedPascalCasePlural: string
  typesPath: string
  navigationItemsCode: string
  inlineOptionsCode: string
  fieldToGroupCode: string
  errorTrackingCode: string
  hierarchyDefaultsCode: string
  hasHierarchy: boolean
  dateInitCode: string
  scriptAdditions: string
  handleSubmitCode: string
}): string {
  const {
    prefixedPascalCase,
    prefixedPascalCasePlural,
    typesPath,
    navigationItemsCode,
    inlineOptionsCode,
    fieldToGroupCode,
    errorTrackingCode,
    hierarchyDefaultsCode,
    hasHierarchy,
    dateInitCode,
    scriptAdditions,
    handleSubmitCode
  } = opts

  return `<script setup lang="ts">
import type { ${prefixedPascalCase}FormProps, ${prefixedPascalCase}FormData } from '${typesPath}'
import use${prefixedPascalCasePlural} from '../composables/use${prefixedPascalCasePlural}'

const props = defineProps<${prefixedPascalCase}FormProps>()
const { defaultValue, schema, collection } = use${prefixedPascalCasePlural}()

// Field labels resolve through translations (team override → system → fallback)
const { t } = useT()

// Form layout configuration
${navigationItemsCode}
${inlineOptionsCode ? `\n// Static select options\n${inlineOptionsCode}\n` : ''}${fieldToGroupCode}
${errorTrackingCode}

// Use new mutation composable for data operations
const { create, update, deleteItems } = useCollectionMutation(collection)

// useCrouton still manages modal state
const { close, loading } = useCrouton()

// Initialize form state with proper values (no watch needed!)${hierarchyDefaultsCode}
const initialValues = props.action === 'update' && props.activeItem?.id
  ? { ...defaultValue, ...props.activeItem }
  : { ...defaultValue${hasHierarchy ? ', ...hierarchyDefaults' : ''} }${dateInitCode}

// Draft state: seeded from defaults (required fields may start null/empty until
// the user fills them; the zod schema validates on submit), so cast the initial
// values to the validated shape.
const state = ref<${prefixedPascalCase}FormData & { id?: string | null }>(initialValues as ${prefixedPascalCase}FormData & { id?: string | null })${scriptAdditions}

${handleSubmitCode}
</script>`
}

export function generateFormComponent(data: Record<string, any>, config: Record<string, any> = {}): string {
  const { pascalCase, pascalCasePlural, layerPascalCase, layerCamelCase, fields, plural, layer, hierarchy } = data
  const prefixedPascalCase = `${layerPascalCase}${pascalCase}`
  const prefixedPascalCasePlural = `${layerPascalCase}${pascalCasePlural}`

  const {
    hasHierarchy,
    parentField,
    translatableFieldNames,
    hasTranslations,
    translatableFields,
    regularFields,
    hasDateFields,
    formEnhancements,
    excludedFieldNames,
    fieldsToDisplay,
    fieldsWithInlineOptions
  } = analyzeFields(data, config)

  // Context handed to the module-scope field/group renderers
  const ctx: FieldMarkupContext = {
    layerCamelCase,
    layerPascalCase,
    pascalCasePlural,
    formEnhancements,
    labelAttr: createLabelAttr(`${layer}.${plural}.fields`)
  }

  const { mainGroups, sidebarGroups } = buildFieldGroups(fieldsToDisplay, fields, excludedFieldNames, formEnhancements)

  // Determine if we should use tabs (multiple main groups)
  const useTabs = mainGroups.size > 1
  // Sidebar is shown if there are sidebar fields OR if hierarchy is enabled (for parent picker)
  const hasSidebar = sidebarGroups.size > 0 || hasHierarchy

  // Generate navigation items from main groups
  const navigationItems = useTabs
    ? Array.from(mainGroups.keys()).map(groupName => ({
        label: humanizeGroupName(groupName),
        value: groupName || 'general'
      }))
    : []

  // Generate main area groups
  const mainAreaMarkup = Array.from(mainGroups.entries())
    .map(([groupName, groupFields]) => buildGroupSection(groupName, groupFields, useTabs, ctx))
    .join('\n\n')

  // Generate sidebar area groups
  const sidebarAreaMarkup = hasSidebar
    ? Array.from(sidebarGroups.entries())
        .map(([groupName, groupFields]) => buildGroupSection(groupName, groupFields, false, ctx))
        .join('\n\n')
    : ''

  // Generate AI context header
  const apiPath = `${layer}-${plural}`
  const aiHeader = generateAIHeader(data, apiPath)

  const templateSection = renderTemplateSection({
    useTabs,
    mainAreaMarkup,
    translationField: buildTranslationField(hasTranslations, translatableFieldNames, translatableFields, plural),
    hasSidebar,
    hasHierarchy,
    parentPickerSection: buildParentPickerSection(hasHierarchy, parentField, layerCamelCase, pascalCasePlural),
    sidebarAreaMarkup
  })

  const scriptSection = renderScriptSection({
    prefixedPascalCase,
    prefixedPascalCasePlural,
    typesPath: '../../types',
    navigationItemsCode: buildNavigationItemsCode(useTabs, navigationItems),
    inlineOptionsCode: buildInlineOptionsCode(fieldsWithInlineOptions),
    fieldToGroupCode: buildFieldToGroupCode(useTabs, mainGroups),
    errorTrackingCode: useTabs ? ERROR_TRACKING_CODE : '',
    hierarchyDefaultsCode: buildHierarchyDefaultsCode(hasHierarchy, hierarchy, parentField),
    hasHierarchy,
    dateInitCode: buildDateInitCode(hasDateFields, regularFields),
    scriptAdditions: (formEnhancements.scriptAdditions || []).join('\n'),
    handleSubmitCode: buildHandleSubmitCode(hasDateFields, regularFields, useTabs)
  })

  return `${aiHeader}${templateSection}

${scriptSection}`
}
