/**
 * @crouton-generated
 * @collection handovers
 * @layer sales
 * @generated 2026-08-03
 *
 * ## AI Context
 * - Main interface: SalesHandover
 * - Form data type: SalesHandoverFormData
 * - New item type: NewSalesHandover
 * - Form props: SalesHandoverFormProps
 * - Fields: id, eventId, orderId
 *
 * ## Common Modifications
 * - Add field: Add to interface and ensure schema matches
 * - Change field type: Update both interface and schema
 * - Add computed field: Add optional property to interface
 *
 * This file was generated by @fyit/crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import type { z } from 'zod'
import type { salesHandoverSchema } from './app/composables/useSalesHandovers'

export interface SalesHandover {
  id: string
  teamId: string
  owner: string
  eventId: string
  orderId: string
  createdAt: Date
  updatedAt: Date
  createdBy: string
  updatedBy: string
  optimisticId?: string
  optimisticAction?: 'create' | 'update' | 'delete'
}

export type SalesHandoverFormData = z.infer<typeof salesHandoverSchema>
// Optional (undefined-including) props also accept null on the WRITE path: the
// server body schema validates non-required fields as .nullish() (#1403 — a
// nullable column round-trips null, and null is how a client clears a field),
// so the create input must admit the validated body. The read interface above
// deliberately stays narrow (form bindings/consumers never want null).
type NullableOptionals<T> = { [K in keyof T]: undefined extends T[K] ? T[K] | null : T[K] }
// New* allows the server-set fields (id, createdBy, updatedBy) as optional — the
// generated POST endpoint provides them; other callers (e.g. seed) may omit them.
export type NewSalesHandover = NullableOptionals<Omit<SalesHandover, 'id' | 'createdAt' | 'updatedAt' | 'createdBy' | 'updatedBy'>> & { id?: string; createdBy?: string; updatedBy?: string }

// Props type for the Form component
export interface SalesHandoverFormProps {
  items: string[] // Array of IDs for delete action
  activeItem: SalesHandover | Record<string, never> // SalesHandover for update, empty object for create
  collection: string
  loading: string
  action: 'create' | 'update' | 'delete'
}