<!--
  @crouton-generated
  @collection handovers
  @layer sales
  @generated 2026-08-03

  ## AI Context
  - Form component for handovers collection
  - Handles: create, update, delete actions
  - API endpoint: /api/teams/[id]/sales-handovers
  - Zod schema: useSalesHandovers() composable
  - Fields: eventId, orderId

  ## Common Modifications
  - Add field: Add UFormField in template, update schema in composable
  - Custom validation: Modify schema in composable
  - Custom field component: Use meta.component in schema JSON
  - Change layout: Modify CroutonFormLayout template slots

  Generated by @fyit/crouton-cli
  Safe to modify - regeneration requires --force flag
-->

<template>
  <CroutonFormActionButton
    v-if="action === 'delete'"
    :action="action"
    :collection="collection"
    :items="items"
    :loading="loading"
    @click="handleSubmit"
  />

  <UForm
    v-else
    :schema="schema"
    :state="state"
    @submit="handleSubmit"
  >
    <CroutonFormLayout>
      <template #main>
      <div class="flex flex-col gap-4 p-1">
        <UFormField :label="t('sales.handovers.fields.eventId', 'Event')" name="eventId" class="not-last:pb-4">
          <CroutonFormReferenceSelect
            v-model="state.eventId"
            collection="salesEvents"
            :label="t('sales.handovers.fields.eventId', 'Event')"
          />
        </UFormField>
        <UFormField :label="t('sales.handovers.fields.orderId', 'Order')" name="orderId" class="not-last:pb-4">
          <CroutonFormReferenceSelect
            v-model="state.orderId"
            collection="salesOrders"
            :label="t('sales.handovers.fields.orderId', 'Order')"
          />
        </UFormField>
      </div>
      </template>

      <template #footer>
        <CroutonFormActionButton
          :action="action"
          :collection="collection"
          :items="items"
          :loading="loading"
        />
      </template>
    </CroutonFormLayout>
  </UForm>
</template>

<script setup lang="ts">
import type { SalesHandoverFormProps, SalesHandoverFormData } from '../../types'
import useSalesHandovers from '../composables/useSalesHandovers'

const props = defineProps<SalesHandoverFormProps>()
const { defaultValue, schema, collection } = useSalesHandovers()

// Field labels resolve through translations (team override → system → fallback)
const { t } = useT()

// Form layout configuration
const tabs = ref(false)



// Use new mutation composable for data operations
const { create, update, deleteItems } = useCollectionMutation(collection)

// useCrouton still manages modal state
const { close, loading } = useCrouton()

// Initialize form state with proper values (no watch needed!)
const initialValues = props.action === 'update' && props.activeItem?.id
  ? { ...defaultValue, ...props.activeItem }
  : { ...defaultValue }

// DB nulls are wire/storage values, not form values (#1415): fall back to the
// field default so the strict form schema never sees null on an untouched
// field. No-op when the default itself is null (dates, dependent fields).
const initialRecord = initialValues as Record<string, unknown>
const defaultRecord = defaultValue as Record<string, unknown>
for (const key of Object.keys(defaultRecord)) {
  if (initialRecord[key] === null && defaultRecord[key] !== null) {
    initialRecord[key] = defaultRecord[key]
  }
}

// Draft state: seeded from defaults (required fields may start null/empty until
// the user fills them; the zod schema validates on submit), so cast the initial
// values to the validated shape.
const state = ref<SalesHandoverFormData & { id?: string | null }>(initialValues as SalesHandoverFormData & { id?: string | null })

const handleSubmit = async () => {
  try {
    if (props.action === 'create') {
      await create(state.value)
    } else if (props.action === 'update' && state.value.id) {
      await update(state.value.id, state.value)
    } else if (props.action === 'delete') {
      await deleteItems(props.items)
    }

    close()

  } catch (error) {
    console.error('Form submission failed:', error)
    // You can add toast notification here if available
    // toast.add({ title: 'Error', description: 'Failed to submit form', color: 'red' })
  }
}
</script>