<!--
  @crouton-generated
  @collection handovers
  @layer sales
  @generated 2026-08-03

  ## AI Context
  - List component for handovers collection
  - Collection name: salesHandovers
  - API endpoint: /api/teams/[id]/sales-handovers
  - Columns composable: useSalesHandovers()
  - Column fields: eventId, orderId

  ## Common Modifications
  - Add column: Update columns array in composable
  - Custom cell template: Add <template #fieldName-cell="{ row }">
  - Change layout: Modify :layout prop (table, list, grid, cards, tree)
  - Add filters: Add query params to useCollectionQuery

  Generated by @fyit/crouton-cli
  Safe to modify - regeneration requires --force flag
-->

<template>
  <CroutonCollection
    :layout="layout"
    collection="salesHandovers"
    :columns="columns"
    :rows="handovers || []"
    :loading="pending"
  >
    <template #header>
      <CroutonTableHeader
        title="SalesHandovers"
        :collection="'salesHandovers'"
        createButton
      />
    </template>
    <template #eventId-cell="{ row }">
      <CroutonItemCardMini
        v-if="row.original.eventId"
        :id="row.original.eventId"
        collection="salesEvents"
      />
    </template>
    <template #orderId-cell="{ row }">
      <CroutonItemCardMini
        v-if="row.original.orderId"
        :id="row.original.orderId"
        collection="salesOrders"
      />
    </template>
  </CroutonCollection>
</template>

<script setup lang="ts">
import useSalesHandovers from '../composables/useSalesHandovers'

const props = withDefaults(defineProps<{
  layout?: any
}>(), {
  layout: 'table'
})

const { columns } = useSalesHandovers()

const { items: handovers, pending } = await useCollectionQuery(
  'salesHandovers'
)

</script>