import { describe, it, expect } from 'vitest'
import { tmplDrizzleConfig } from '../../lib/scaffold-app.ts'

// WS2 (#1449): the scaffolded drizzle.config.ts switches from the Nuxt-built
// bundle (.nuxt/hub/db/schema.mjs) to RUNTIME resolution via the WS1a resolver,
// so `drizzle-kit generate` needs no Nuxt build. Two probe findings are encoded:
//   - import specifier MUST carry the explicit .ts extension (esbuild resolution)
//   - `out` MUST stay relative (drizzle-kit 0.31.10 re-reads meta/ via a ./ join;
//     an absolute out ENOENTs on the second run)

describe('tmplDrizzleConfig (WS2 runtime-resolution template)', () => {
  const cfg = tmplDrizzleConfig()

  it('resolves the schema list at runtime via the sync resolver', () => {
    expect(cfg).toContain('resolveSchemaSourcesSync')
    expect(cfg).toMatch(/resolveSchemaSourcesSync\(\s*process\.cwd\(\)/)
  })

  it('imports the resolver with an explicit .ts extension', () => {
    expect(cfg).toContain('@fyit/crouton-cli/lib/utils/schema-sources.ts')
  })

  it('no longer references the Nuxt-built schema bundle', () => {
    expect(cfg).not.toContain('.nuxt/hub/db/schema.mjs')
    expect(cfg).not.toContain('schema.mjs')
  })

  it('keeps `out` relative (no absolute path baked in)', () => {
    expect(cfg).toContain('out: \'server/db/migrations/sqlite\'')
    expect(cfg).not.toMatch(/out:\s*['"]\//)
  })

  it('carries a do-not-hand-edit regeneration header', () => {
    expect(cfg.toLowerCase()).toMatch(/regenerated by crouton|do not (hand-)?edit/)
  })

  it('does not use top-level await (drizzle-kit config is CJS)', () => {
    expect(cfg).not.toMatch(/^\s*(const|let)\s+\w+\s*=\s*await /m)
    expect(cfg).not.toMatch(/await resolveSchemaSources/)
  })
})
