export default {
  // Feature flags - which crouton packages to enable
  features: {
    bookings: { config: { email: { enabled: true } } },
    pages: true,
    maps: true,
    // crouton-layout is `bundled: true` (default-on). Velo doesn't use the layout
    // engine, so opt out explicitly — otherwise `crouton config` writes it back
    // into `extends` and the module warns on every build (#1454).
    layout: false
  },

  // Collections generated by Schema Designer
  collections: [
    { name: 'booking', fieldsFile: './schemas/booking.json' },
    { name: 'location', fieldsFile: './schemas/location.json', formComponent: 'CroutonBookingsLocationForm' },
    { name: 'settings', fieldsFile: './schemas/settings.json' },
    { name: 'pages', fieldsFile: './schemas/pages.json', formComponent: 'CroutonPagesForm', hierarchy: { enabled: true, parentField: 'parentId', orderField: 'order', pathField: 'path', depthField: 'depth' } }
  ],

  // Target layers
  targets: [
    { layer: 'bookings', collections: ['booking', 'location', 'settings'] },
    { layer: 'pages', collections: ['pages'] }
  ],

  dialect: 'sqlite'
}
