/**
 * @crouton-generated
 * @collection handovers
 * @layer sales
 * @generated 2026-08-03
 *
 * ## AI Context
 * - Composable: useSalesHandovers
 * - Collection name: salesHandovers
 * - API endpoint: /api/teams/[id]/sales-handovers
 * - Form component: SalesHandoversForm
 * - List component: SalesHandoversList
 * - Fields: id, eventId, orderId
 *
 * ## Common Modifications
 * - Add field: Add to schema object and defaultValues
 * - Change validation: Modify z.object() schema
 * - Add column: Add to columns array
 * - Change API path: Modify apiPath in config
 *
 * This file was generated by @fyit/crouton-cli
 * Safe to modify - regeneration requires --force flag
 */

import { z } from 'zod'

// Schema exported separately - Zod 4 schemas cannot survive deep cloning
// Keep schema outside of objects that might be serialized/cloned during SSR
export const salesHandoverSchema = z.object({
  eventId: z.string().min(1, 'eventId is required'),
  orderId: z.string().min(1, 'orderId is required')
})

export const salesHandoversColumns = [
  { accessorKey: 'id', header: 'Id' },
  { accessorKey: 'eventId', header: 'EventId' },
  { accessorKey: 'orderId', header: 'OrderId' }
]

// Config object WITHOUT schema - safe for SSR serialization
const _salesHandoversConfig = {
  name: 'salesHandovers',
  layer: 'sales',
  apiPath: 'sales-handovers',
  componentName: 'SalesHandoversForm',
  defaultValues: {
    eventId: '',
    orderId: ''
  },
  columns: salesHandoversColumns,
  fields: [
      {
          "name": "eventId",
          "type": "string",
          "label": "Event",
          "area": "main"
      },
      {
          "name": "orderId",
          "type": "string",
          "label": "Order",
          "area": "main"
      }
  ],
}

// Add schema as non-enumerable property so klona skips it during cloning
Object.defineProperty(_salesHandoversConfig, 'schema', {
  value: salesHandoverSchema,
  enumerable: false,
  configurable: false,
  writable: false
})

export const salesHandoversConfig = _salesHandoversConfig as typeof _salesHandoversConfig & { schema: typeof salesHandoverSchema }

export const useSalesHandovers = () => salesHandoversConfig

// Default export for auto-import compatibility
export default function () {
  return {
    defaultValue: salesHandoversConfig.defaultValues,
    schema: salesHandoverSchema,
    columns: salesHandoversConfig.columns,
    collection: salesHandoversConfig.name
  }
}