// Regenerated by crouton — do not hand-edit.
import { defineConfig } from 'drizzle-kit'
import { resolveSchemaSourcesSync } from '@fyit/crouton-cli/lib/utils/schema-sources.ts'

export default defineConfig({
  dialect: 'sqlite',
  schema: resolveSchemaSourcesSync(process.cwd()),
  out: 'server/db/migrations/sqlite',
})
